### PR TITLE
Adjustment rewrite

### PR DESCRIPTION
**Pull request by dill**
* order argument to ds() is now only used to specify order, to fix a given number of adjustments use the new argument nadj (see ?ds for more info)
* fix bug where polynomial adjustments started at the wrong order (2 rather than 4)

based on #115 and #117

### CODE REVIEW

**Comment by lenthomas** [comment]
Thanks @dill I'll check this over on Sunday 6th March at the latest.

**Comment by lenthomas** [comment]
Dave, looks like there's an error in the unif+poly and unif+hermite.  They start with order 4 when they should start with order 2.  Here's my test code, annotated:

```
library(Distance)
data(book.tee.data)
tee.data <- subset(book.tee.data$book.tee.dataframe, observer == 1)

#Correctly fits hn and then hn+cos(2)
ds.model <- ds(tee.data, trunc = 4, key = "hn", adj = "cos")
#Correctly fits hn and then hn+cos(4)
ds.model <- ds(tee.data, trunc = 4, key = "hn", adj = "poly")
#Correctly fits hn and then hn+herm(4)
ds.model <- ds(tee.data, trunc = 4, key = "hn", adj = "herm")

#Correctly fits hr and then hn+cos(2) (and then hn+cos(3))
ds.model <- ds(tee.data, trunc = 4, key = "hr", adj = "cos")
#Correctly fits hn+poly(4) (then hn+poly(6), etc)
ds.model <- ds(tee.data, trunc = 4, key = "hr", adj = "poly")
#Correctly fits hr and then hn+herm(4)
ds.model <- ds(tee.data, trunc = 4, key = "hr", adj = "herm")

#I note that uniform key function fits at least one adjustment term by default
#Given this:
#Correctly fits unif+cos(1) and then unif+cos(2)
ds.model <- ds(tee.data, trunc = 4, key = "unif", adj = "cos")
#Incorrectly fits unif+poly(4) first
# the first model tried should be unif+poly(2) (and then unif+poly(4) etc)
ds.model <- ds(tee.data, trunc = 4, key = "unif", adj = "poly")
#Incorrectly fits unif+herm(4) first
# the first model tried should be unif+herm(2) (and then unif+herm(4) etc)
ds.model <- ds(tee.data, trunc = 4, key = "unif", adj = "herm")
```

On viewing the code in `ds.R` it looks like lines 487-8 may be the problem.  Shouldn't 

```
          # simple and Hermite poly: even from 4
          order <- seq(4, by=2, length.out=max_adjustments)
```
be
```
          # simple and Hermite poly: even from 2
          order <- seq(2, by=2, length.out=max_adjustments)
```
?

There may be something I'm missing here.

**Comment by lenthomas** [comment]
I did a test of the "order" argument.  Mostly OK, but 
- unif + herm(2) is not allowed when it should be
- hn + cos(2) is allowed when it should not be
- I didn't test hr + cos(2) but I expect that's the same
- a few other odd messages as documented below

```
#Test of the order argument
#Try to fit a unif+cos(1)
#OK
ds.model <- ds(tee.data, trunc = 4, key = "unif", adj = "cos", order= 1)
#Try to fit unif+cos(2)
#OK (well didn't work but it tried)
ds.model <- ds(tee.data, trunc = 4, key = "unif", adj = "cos", order= 2)
#Try to fit unif+cos(1, 2)
#OK
ds.model <- ds(tee.data, trunc = 4, key = "unif", adj = "cos", order= c(1,2))

#Try to fit a unif+poly(1)
#OK - gives error message "Adjustment orders must be even for simple polynomials"
ds.model <- ds(tee.data, trunc = 4, key = "unif", adj = "poly", order= 1)
#Try to fit a unif+poly(2)
#OK
ds.model <- ds(tee.data, trunc = 4, key = "unif", adj = "poly", order= 2)
#Try to fit a unif+poly(4)
#OK
ds.model <- ds(tee.data, trunc = 4, key = "unif", adj = "poly", order= 4)
#Try to fit a unif+poly(2, 4)
#OK
ds.model <- ds(tee.data, trunc = 4, key = "unif", adj = "poly", order= c(2,4))
#Try to fit a unif+poly(3, 4)
#OK - gives error message "Adjustment orders must be even for simple polynomials"
ds.model <- ds(tee.data, trunc = 4, key = "unif", adj = "poly", order= c(3,4))

#Try to fit a unif+herm(1)
#Hmm... gives error message "Hermite polynomial adjustment terms of order < 4 selected"
# when I would expect "Adjustment orders must be even for simple hermnomials"
# doesn't bode well for the next test
ds.model <- ds(tee.data, trunc = 4, key = "unif", adj = "herm", order= 1)
#Try to fit a unif+herm(2)
#Incorrectly gives error message "Hermite polynomial adjustment terms of order < 4 selected" 
ds.model <- ds(tee.data, trunc = 4, key = "unif", adj = "herm", order= 2)
#Try to fit a unif+herm(4)
#OK
ds.model <- ds(tee.data, trunc = 4, key = "unif", adj = "herm", order= 4)


#Try to fit a hn+cos(1)
#Hmm... strange error message "Adjustment orders for Hermite polynomials and cosines must start at 2."
# It's right about cos, but for Hermite the lowest order allowed should be 4 
ds.model <- ds(tee.data, trunc = 4, key = "hn", adj = "cos", order= 1)
#Try to fit hn+cos(2)
#OK
ds.model <- ds(tee.data, trunc = 4, key = "hn", adj = "cos", order= 2)
#Try to fit hn+cos(1, 2)
#OK - but same strange error message as above
ds.model <- ds(tee.data, trunc = 4, key = "hn", adj = "cos", order= c(1,2))

#Try to fit a hn+poly(1)
#OK
ds.model <- ds(tee.data, trunc = 4, key = "hn", adj = "poly", order= 1)
#Try to fit a hn+poly(2)
#Incorrectly allows this - lowest order allowed should be 4
ds.model <- ds(tee.data, trunc = 4, key = "hn", adj = "poly", order= 2)
#Try to fit a hn+poly(4)
#OK
ds.model <- ds(tee.data, trunc = 4, key = "hn", adj = "poly", order= 4)

#Try to fit a hn+herm(1)
#Hmm... gives strange error message as documented previously -
# should just stick to checking it's even (and 4 or more)
ds.model <- ds(tee.data, trunc = 4, key = "hn", adj = "herm", order= 1)
#Try to fit a hn+herm(2)
#OK - gives correct error message "Hermite polynomial adjustment terms of order < 4 selected"
ds.model <- ds(tee.data, trunc = 4, key = "hn", adj = "herm", order= 2)
#Try to fit a hn+herm(4)
#OK
ds.model <- ds(tee.data, trunc = 4, key = "hn", adj = "herm", order= 4)

#Ran out of steam at this point
```

**Comment by lenthomas** [comment]
On superficial test of the `nadj` argument, it seems to work (without the `order` argument - see below) in giving the right number of adjustments.  But it does not work with unif + herm likely for the same reason as documented above.
```
ds.model <- ds(tee.data, trunc = 4, key = "hn", adj = "herm", nadj = 2)
ds.model <- ds(tee.data, trunc = 4, key = "unif", adj = "herm", nadj = 2)
```
The latter should fit unif + herm(2, 4) but it fits unif + herm (4, 6)

Also, nadj it seems not to work correctly with the order argument.  The documentation for the order argument says `The number of adjustment terms specified here must match nadj (or nadj can be the default NULL value).` which means the second line below should not work, but it does (it just fits the one order specified by `order`):

```
#Quick test of nadj
#OK
ds.model <- ds(tee.data, trunc = 4, key = "hn", adj = "herm", nadj = 1, order= 4)
#Shouldn't work but does
ds.model <- ds(tee.data, trunc = 4, key = "hn", adj = "herm", nadj = 2, order= 4)
```
Shouldn't the second line yield an error message?

**Comment by dill** [comment]
@lenthomas hmm. Going through your first list:

 - *unif + herm(2) is not allowed when it should be* not clear what the rule should be here as it's not in the book... is this what Distance for Windows does? Fixed in 8f9e0ea
 - *hn + cos(2) is allowed when it should not be* pretty sure that's the right thing, looking at the definitions you posted [here](https://github.com/DistanceDevelopment/Distance/issues/117#issuecomment-1060395948)?
 - *I didn't test hr + cos(2) but I expect that's the same* as above?
 - *a few other odd messages as documented below*:
   - `unif+poly(1)` *should not be allowed (should start from 2)*. Fixed in 8f9e0ea
   - `unif+herm(1)` gives wrong error message. `mrds` bug, fixed in [06f071a](https://github.com/DistanceDevelopment/mrds/commit/06f071afb87e9675472a657c688f5b9977169828)
   - `hn+cos(1)` *strange error message "Adjustment orders for Hermite polynomials and cosines must start at 2." It's right about cos, but for Hermite the lowest order allowed should be 4.* Removed this (d07fb19), falling back to `mrds` checks.

**Comment by dill** [comment]
Error message when `length(order)!=nadj` in 2403d95

**Comment by lenthomas** [comment]
I'm afraid uniform + cosine still fails.  See code below (last test tried).  Would it be possible for you to test with this code before posting the next version?  

(I'll now try the other code I posted (testing `order` and `nadj`...) )

```
library(Distance)
data(book.tee.data)
tee.data <- subset(book.tee.data$book.tee.dataframe, observer == 1)

#Correctly fits hn and then hn+cos(2)
ds.model <- ds(tee.data, trunc = 4, key = "hn", adj = "cos")
#Correctly fits hn and then hn+cos(4)
ds.model <- ds(tee.data, trunc = 4, key = "hn", adj = "poly")
#Correctly fits hn and then hn+herm(4)
ds.model <- ds(tee.data, trunc = 4, key = "hn", adj = "herm")

#Correctly fits hr and then hn+cos(2) (and then hn+cos(3))
ds.model <- ds(tee.data, trunc = 4, key = "hr", adj = "cos")
#Correctly fits hn+poly(4) (then hn+poly(6), etc)
ds.model <- ds(tee.data, trunc = 4, key = "hr", adj = "poly")
#Correctly fits hr and then hn+herm(4)
ds.model <- ds(tee.data, trunc = 4, key = "hr", adj = "herm")

#I note that uniform key function fits at least one adjustment term by default
#Given this:
#Correctly fits unif+cos(1) and then unif+cos(2)
ds.model <- ds(tee.data, trunc = 4, key = "unif", adj = "cos")
#Correctly fits unif+poly(2) then unif+poly(2, 4)
ds.model <- ds(tee.data, trunc = 4, key = "unif", adj = "poly")
#Correctly tries unif+herm(2) but then incorrectly
# throws an error message
#"Error in adj.check.order(adj.series, adj.order, key) : 
# Hermite polynomial adjustment terms of order < 4 selected"
ds.model <- ds(tee.data, trunc = 4, key = "unif", adj = "herm")
```

**Comment by lenthomas** [comment]
Test of the `order` argument, running the same code I did before.  Two tests that previously failed are still failing:
- unif + herm(2) fails when it shouldn't (likely same error as reported just now)
- hn + poly(2) is allowed when it should not be

Code below.  Would it be possible to test with this code also before posting the next version?

```
#Test of the order argument
#Try to fit a unif+cos(1)
#OK
ds.model <- ds(tee.data, trunc = 4, key = "unif", adj = "cos", order= 1)
#Try to fit unif+cos(2)
#OK (well didn't work but it tried)
ds.model <- ds(tee.data, trunc = 4, key = "unif", adj = "cos", order= 2)
#Try to fit unif+cos(1, 2)
#OK
ds.model <- ds(tee.data, trunc = 4, key = "unif", adj = "cos", order= c(1,2))

#Try to fit a unif+poly(1)
#OK - gives error message "Odd polynomial adjustment terms selected"
ds.model <- ds(tee.data, trunc = 4, key = "unif", adj = "poly", order= 1)
#Try to fit a unif+poly(2)
#OK
ds.model <- ds(tee.data, trunc = 4, key = "unif", adj = "poly", order= 2)
#Try to fit a unif+poly(4)
#OK
ds.model <- ds(tee.data, trunc = 4, key = "unif", adj = "poly", order= 4)
#Try to fit a unif+poly(2, 4)
#OK
ds.model <- ds(tee.data, trunc = 4, key = "unif", adj = "poly", order= c(2,4))
#Try to fit a unif+poly(3, 4)
#OK - gives error message "Odd polynomial adjustment terms selected"
ds.model <- ds(tee.data, trunc = 4, key = "unif", adj = "poly", order= c(3,4))

#Try to fit a unif+herm(1)
#OK - gives error message "Hermite polynomial adjustment terms of order < 4 selected"
ds.model <- ds(tee.data, trunc = 4, key = "unif", adj = "herm", order= 1)
#Try to fit a unif+herm(2)
#Incorrectly gives error message "Hermite polynomial adjustment terms of order < 4 selected" 
#This issue was reported previously
ds.model <- ds(tee.data, trunc = 4, key = "unif", adj = "herm", order= 2)
#Try to fit a unif+herm(4)
#OK
ds.model <- ds(tee.data, trunc = 4, key = "unif", adj = "herm", order= 4)


#Try to fit a hn+cos(1)
#OK - get error message "Cosine adjustments must be of order >2 for half-normal key functions"
ds.model <- ds(tee.data, trunc = 4, key = "hn", adj = "cos", order= 1)
#Try to fit hn+cos(2)
#OK
ds.model <- ds(tee.data, trunc = 4, key = "hn", adj = "cos", order= 2)
#Try to fit hn+cos(1, 2)
#OK - get same error message as above
ds.model <- ds(tee.data, trunc = 4, key = "hn", adj = "cos", order= c(1,2))

#Try to fit a hn+poly(1)
#OK - get error message "Odd polynomial adjustment terms selected"
ds.model <- ds(tee.data, trunc = 4, key = "hn", adj = "poly", order= 1)
#Try to fit a hn+poly(2)
#Incorrectly allows this - lowest order allowed should be 4
#This problem was reported previously
ds.model <- ds(tee.data, trunc = 4, key = "hn", adj = "poly", order= 2)
#Try to fit a hn+poly(4)
#OK
ds.model <- ds(tee.data, trunc = 4, key = "hn", adj = "poly", order= 4)

#Try to fit a hn+herm(1)
#OK - get error message "Hermite polynomial adjustment terms of order < 4 selected"
ds.model <- ds(tee.data, trunc = 4, key = "hn", adj = "herm", order= 1)
#Try to fit a hn+herm(2)
#OK - gives correct error message "Hermite polynomial adjustment terms of order < 4 selected"
ds.model <- ds(tee.data, trunc = 4, key = "hn", adj = "herm", order= 2)
#Try to fit a hn+herm(4)
#OK
ds.model <- ds(tee.data, trunc = 4, key = "hn", adj = "herm", order= 4)
```

**Pull request merged**
