### PR TITLE
Camera trapping work

### LINKED ISSUE #99: QAIC for model selection
See [here](https://examples.distancesampling.org/Distance-cameratraps/camera-distill.html#model-selection-adjustments-from-overdispersion) for code implementing the QAIC of:

Howe, E. J., Buckland, S. T., Després-Einspenner, M.-L., & Kühl, H. S. (2019). Model selection with overdispersed distance sampling data. Methods in Ecology and Evolution, 10(1), 38–47. 10.1111/2041-210X.13082

### PR DESCRIPTION
**Pull request by dill**
Hi folks (@erex, @lenthomas) is it possible to merge this branch now (and close #99 and #100)?

### CODE REVIEW

**Review by erex — COMMENTED** [review]
I'm happy to sign off on issues #100 and #101, but what is the current version number, should it be boosted to 1.0.4.  Will this be submitted to CRAN as 1.0.4?

**Comment by dill** [comment]
There are still [other issues](https://github.com/DistanceDevelopment/Distance/milestone/4) to resolve for 1.0.4, but to move ahead on these without wasting time on merge conflicts I'd like to merge the CTDS changes first.

**Comment by erex** [comment]
Understood, so this is not 1.0.4 as of yet.

**Comment by dill** [comment]
Correct, once the other issues are sorted out it will be.

**Pull request merged**
